# Generated by Django 3.2.8 on 2021-12-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='amount',
        ),
        migrations.AddField(
            model_name='cost',
            name='amount_cost',
            field=models.IntegerField(default=0, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='finance',
            name='expected_amount',
            field=models.IntegerField(default=0, verbose_name='Expected amount'),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
