# Generated by Django 3.2.8 on 2021-12-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211206_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizen_code',
            field=models.CharField(blank=True, max_length=11, verbose_name='Citizen code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone number'),
        ),
    ]
