# Generated by Django 3.2.8 on 2021-12-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211206_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizen_code',
            field=models.CharField(max_length=11, verbose_name='Citizen code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
    ]
